/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Accommodation Type
 * Id: e7a3d931-83de-48cc-895e-06ffe3f73147
 * Codename: accommodation_type
 */
export type AccommodationType = 'rooms' | 'tents';
