import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Country
 * Id: 699e98e5-583e-4fb0-8c6a-2d033118b681
 * Codename: country
 */
export type Country = IContentItem<{
  /**
   * Code (text)
   * Required: true
   * Id: c1be40d0-ad48-4e31-ba5b-d490a6e00fb5
   * Codename: code
   */
  code: Elements.TextElement;
}>;
