import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HotelListing } from './hotel_listing';

/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Homepage
 * Id: 553068b7-7051-4db8-9da0-13184bb7068b
 * Codename: homepage
 */
export type Homepage = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: 28eef3ca-b4b7-4e35-8817-4b2089d1b5ec
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Subpages (subpages)
   * Required: false
   * Id: 46868dc4-8a36-467f-86af-39454d4b7c07
   * Codename: subpages
   */
  subpages: Elements.LinkedItemsElement<HotelListing>;

  /**
   * Content (modular_content)
   * Required: false
   * Id: f80abb51-a52f-48aa-b79e-8d48e974d3c1
   * Codename: content
   */
  content: Elements.LinkedItemsElement<IContentItem>;
}>;
