import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { AccommodationType } from '../taxonomies/accommodation_type';
import { Room } from './room';

/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Room Group
 * Id: 9c4e528e-6074-4470-82d4-2613f5548bbb
 * Codename: room_group
 */
export type RoomGroup = IContentItem<{
  /**
   * Accommodation Type (taxonomy)
   * Required: true
   * Id: 38dab755-2b40-4174-90c7-4d1176494c7f
   * Codename: accommodation_type
   */
  accommodation_type: Elements.TaxonomyElement<AccommodationType>;

  /**
   * Description (text)
   * Required: true
   * Id: fe0e62f5-2513-4065-b8f0-af5ff3cb5be3
   * Codename: description
   */
  description: Elements.TextElement;

  /**
   * Rooms (modular_content)
   * Required: false
   * Id: a8a8292d-e0dd-42d2-9879-859e8be397e7
   * Codename: rooms
   */
  rooms: Elements.LinkedItemsElement<Room>;
}>;
