import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Room
 * Id: 95184000-049b-42e5-8f8e-ea27cf289851
 * Codename: room
 */
export type Room = IContentItem<{
  /**
   * Code (text)
   * Required: true
   * Id: 6316821a-e215-4de1-ad40-2aa86015c9e5
   * Codename: code
   */
  code: Elements.TextElement;

  /**
   * Long description (text)
   * Required: true
   * Id: 40e81b00-cda8-4701-a428-61e096a33d22
   * Codename: long_description
   */
  long_description: Elements.TextElement;

  /**
   * Short description (text)
   * Required: false
   * Id: 9c7d915b-ac3b-412d-bbdb-300656498832
   * Codename: short_description
   */
  short_description: Elements.TextElement;
}>;
