/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Project name: LuxAir
 * Environment: Production
 * Project Id: 4aa67922-1f3b-017c-68ee-b6ab41480239
 */
export const collections = {
  /**
   * Default
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
};
