/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Project name: LuxAir
 * Environment: Production
 * Project Id: 4aa67922-1f3b-017c-68ee-b6ab41480239
 */
export const roles = {
  /**
   * Project manager
   */
  projectManager: {
    codename: 'project-manager',
    id: '5c8fbce1-15b8-4b7f-8f12-dd6ac40ca18e',
    name: 'Project manager',
  },
};
