/**
 * Generated by '@kontent-ai/model-generator@5.4.1'
 *
 * Project name: LuxAir
 * Environment: Production
 * Project Id: 4aa67922-1f3b-017c-68ee-b6ab41480239
 */
export const taxonomies = {
  /**
   * Accommodation Type
   */
  accommodation_type: {
    codename: 'accommodation_type',
    id: 'e7a3d931-83de-48cc-895e-06ffe3f73147',
    externalId: undefined,
    name: 'Accommodation Type',
    terms: {
      rooms: {
        codename: 'rooms',
        id: 'c1bda571-d4bb-455e-8b82-4f2d97c8dc2f',
        externalId: undefined,
        name: 'Rooms',
        terms: {},
      },
      tents: {
        codename: 'tents',
        id: 'fc124b2d-3318-40aa-938b-390ad81010b1',
        externalId: undefined,
        name: 'Tents',
        terms: {},
      },
    },
  },

  /**
   * Season
   */
  season: {
    codename: 'season',
    id: '0b86220c-001e-4c6c-865b-edc999ed0a5d',
    externalId: undefined,
    name: 'Season',
    terms: {
      s2: {
        codename: 's2',
        id: 'd2114822-5aa6-4cbb-a9ab-3fac2f79f8bb',
        externalId: undefined,
        name: 'S2',
        terms: {},
      },
    },
  },

  /**
   * Tour operator
   */
  tour_operator: {
    codename: 'tour_operator',
    id: '73f92844-0a2e-4a81-8ebd-185ecf23fddb',
    externalId: undefined,
    name: 'Tour operator',
    terms: {
      lux: {
        codename: 'lux',
        id: '4dc47e82-cef0-4eac-af0a-0fd4433089fc',
        externalId: undefined,
        name: 'LUX',
        terms: {},
      },
    },
  },
};
